version: "3.7"
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./dbvolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=voxel
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "127.0.0.1:3336:3016"
  node:
    build: .
    init: true
    restart: always
    environment:
      - BZON_DECOMP_URL=
      - NEOS_BOT_ID=
      - NEOS_BOT_PASSWORD=
    ports:
      - "127.0.0.1:3015:3000"